version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 5672:5672
      - 15672:15672